### ISSUE TITLE
Critical JSON Nesting Malform Issue!

### ISSUE THREAD

**Issue by jabcreations** [gsuitedevs/browser-samples#12] opened 2018-08-04 20:30 UTC
So working with the following code:

```
function event_create()
{
 var event = {
  'summary': 'Google I/O 2015',
  'location': '800 Howard St., San Francisco, CA 94103',
  'description': 'A chance to hear more about Google\'s developer products.',
  'start': {
    'dateTime': '2018-08-04T09:00:00-07:00',
    'timeZone': 'America/Los_Angeles'
  },
  'end': {
    'dateTime': '2018-08-04T17:00:00-07:00',
    'timeZone': 'America/Los_Angeles'
  },
  'recurrence': [
    'RRULE:FREQ=DAILY;COUNT=2'
  ],
  'attendees': [
    {'email': 'lpage@example.com'},
    {'email': 'sbrin@example.com'}
  ],
  'reminders': {
    'useDefault': false,
    'overrides': [
      {'method': 'email', 'minutes': 24 * 60},
      {'method': 'popup', 'minutes': 10}
    ]
  }
 };
console.log(event);
 var request = gapi.client.calendar.events.insert({'calendarId': 'primary', 'resource': event});
console.log('request...');
console.log(request);
 request.execute(function(event) {appendPre('Event created: ' + event.htmlLink);});
}
```

When I run it from the test file to create the event the `console.log(request);` reveals the following:

`Zq.k5.body = "{"summary":"Google I/O 2015","location":"800...`

However (even after clearing cache/cookies) when I run the live code, the exact same code though from a different URL the request produces extra JSON:

`Zq.k5.body = "{"resource":{"summary":"Google I/O 2015","location":"800...`

_That_ in turn results in HTTP 400: **Missing end time.**

Of course the end time is missing, a whole extra parent element (**"resource":**) is pointlessly added to the JSON data being sent! I have no idea _why_ this is happening. I do know _lots_ of people have been encountering the issue without realizing that the JSON data is effectively broken (valid in a validator only). I have an entire project on hold for three days (don't feel bad or apologize, everyone who writes code gets bugs) though as I have other things I can work on. However I would greatly appreciate you folks taking care of this ASAP.

**Comment by jabcreations** [comment] 2018-08-05 16:36
So I'm trying to track down this issue in hopes that it'll save you folks the time when you get back:

This line:

`!q && 1 == _.qA(n) && n.hasOwnProperty("resource") && (q = "resource");`

In this file looks suspicious:

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.Y_wrh8DxACY.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCOrxii_3Shdq8FvYwaX1-pLTZLNeQ/cb=gapi.loaded_0

I couldn't find the string `"resource"` in any of the other requested files. I went poking around though the methods and properties have pointlessly short single character names.

**Comment by erickoledadevrel** [comment] 2018-08-27 14:36
Sorry for the slow reply. Have you had any luck figuring this out? I haven't been able to reproduce the problem, and it seems to be something specific to your production environment. Are you loading the libraries the same way there?

**Comment by jabcreations** [comment] 2018-08-29 08:41
Hi Erick,
If you'd like to review a live test environment register at [jabcreations.net](https://www.jabcreations.net/), post your user name here and I'll upgrade that account to have enough permissions to view the scenario. I'll also have JavaScript `console.log` before and after my fix so you have a bit more useful scenario to work with.

**Comment by grant** [comment] 2018-11-08 10:33
Is this still an issue?

**Comment by jabcreations** [comment] 2018-11-08 18:17
Very likely yes. I wrote the code so that it would work even if you guys fixed it. Please register an account at jabcreations.net (just a test domain) and I'll ensure that the code consoles what is going on. I'll upgrade your account once you let me know you've set it up so you have access for testing.

**Comment by erickoledadevrel** [comment] 2018-11-09 20:48
I'm personally not comfortable debugging code on your production site. If you can find a way to replicate the problem on the test page or domain I'd be happy to take a look.

**Comment by erickoledadevrel** [comment] 2018-11-12 15:17
Thank you for your effort so far, and I appreciate that you don't have the time to invest in further narrowing down this issue. Unfortunately we have a policy of not debugging developers' code directly, and rely on our users to provide repro cases. At the moment you are the only developer reporting this issue, and the problem could be due to interactions with other libraries loaded in your application, etc. If there is an issue on Google's end it almost certainly is in the [JavaScript client library](https://github.com/google/google-api-javascript-client), and it may make sense to work with that team going forward. I'm closing this issue for now.

**Closed by erickoledadevrel** 2018-11-12 15:17 UTC

**Comment by jabcreations** [comment] 2018-11-12 21:31
I've posted this bug report here: https://github.com/google/google-api-javascript-client/issues/482
